In [1]:
import pandas as pd

In [2]:
s=pd.Series([1, 2, 3, 4, 5])
print(s)

0    1
1    2
2    3
3    4
4    5
dtype: int64

1. Create a dataframe with the following data

| Emp_ID | Name  | Department | Salary | Experience |
| ------ | ----- | ---------- | ------ | ---------- |
| 101    | Ravi  | IT         | 60000  | 3          |
| 102    | Priya | HR         | 45000  | 2          |
| 103    | Kiran | IT         | 70000  | 5          |
| 104    | Sneha | Finance    | 65000  | 4          |
| 105    | Arjun | HR         | 50000  | 3          |

1.1. Create the DataFrame with the above data

In [3]:
df=pd.DataFrame({
    "Emp_ID ": [101, 102, 103, 104, 105],
    "Name":["Ravi","Priya","Kiran","Shena","Arjun"],
    "Department":["IT","HR","IT","Finance","HR"],
    "Salary":[60000, 45000, 70000, 65000, 50000],
    "Experience":[3, 2, 5, 4, 3]
})

In [4]:
df

   Emp_ID    Name Department  Salary  Experience
0      101   Ravi         IT   60000           3
1      102  Priya         HR   45000           2
2      103  Kiran         IT   70000           5
3      104  Shena    Finance   65000           4
4      105  Arjun         HR   50000           3

1.2. Display column names.

In [5]:
df.columns

Index(['Emp_ID ', 'Name', 'Department', 'Salary', 'Experience'], dtype='object')

In [6]:
df['Department']

0         IT
1         HR
2         IT
3    Finance
4         HR
Name: Department, dtype: object

1.3. Find the shape of the DataFrame.

In [7]:
df.shape

(5, 5)

1.4. Get summary statistics.

In [8]:
df.describe()

          Emp_ID         Salary  Experience
count    5.000000      5.000000    5.000000
mean   103.000000  58000.000000    3.400000
std      1.581139  10368.220677    1.140175
min    101.000000  45000.000000    2.000000
25%    102.000000  50000.000000    3.000000
50%    103.000000  60000.000000    3.000000
75%    104.000000  65000.000000    4.000000
max    105.000000  70000.000000    5.000000

1.5. Display data types of all columns.

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Emp_ID      5 non-null      int64
 1   Name        5 non-null      object
 2   Department  5 non-null      object
 3   Salary      5 non-null      int64
 4   Experience  5 non-null      int64
dtypes: int64(3), object(2)
memory usage: 328.0+ bytes

2. Display employees whose salary is greater than 55,000.

In [10]:
df[df['Salary']>55000]

   Emp_ID    Name Department  Salary  Experience
0      101   Ravi         IT   60000           3
2      103  Kiran         IT   70000           5
3      104  Shena    Finance   65000           4

3. Find employees whose salary is between 50,000 and 70,000.

In [11]:
df[(df['Salary'] >= 50000) & (df['Salary'] <= 70000)]

   Emp_ID    Name Department  Salary  Experience
0      101   Ravi         IT   60000           3
2      103  Kiran         IT   70000           5
3      104  Shena    Finance   65000           4
4      105  Arjun         HR   50000           3

4. Sort employees by salary in descending order.

In [12]:
df.sort_values('Salary', ascending=False)

   Emp_ID    Name Department  Salary  Experience
2      103  Kiran         IT   70000           5
3      104  Shena    Finance   65000           4
0      101   Ravi         IT   60000           3
4      105  Arjun         HR   50000           3
1      102  Priya         HR   45000           2

5. Display only Name and Salary columns.

In [13]:
df[['Name','Salary']]

    Name  Salary
0   Ravi   60000
1  Priya   45000
2  Kiran   70000
3  Shena   65000
4  Arjun   50000

6. Display the last 2 employees.

In [14]:
df.tail(2)

   Emp_ID    Name Department  Salary  Experience
3      104  Shena    Finance   65000           4
4      105  Arjun         HR   50000           3

In [15]:
df.iloc[3:5]

   Emp_ID    Name Department  Salary  Experience
3      104  Shena    Finance   65000           4
4      105  Arjun         HR   50000           3

7. Create the following dataframe

| Student | Marks | City      |
| ------- | ----- | --------- |
| A       | 85    | Hyderabad |
| B       | NaN   | Chennai   |
| C       | 92    | NaN       |
| D       | 78    | Bangalore |
| E       | NaN   | Mumbai    |

In [16]:
import numpy as np
df1=pd.DataFrame({
    "Student":['A','B','C','D','E'],
    "Marks":[85,np.nan,92,78,np.nan],
    "City":["Hyderbad","Chennai",np.nan,"Bangalore","Mumbai"]

})

In [17]:
df1

  Student  Marks       City
0       A   85.0   Hyderbad
1       B    NaN    Chennai
2       C   92.0        NaN
3       D   78.0  Bangalore
4       E    NaN     Mumbai

 7.1 Find total missing values in each column.

In [18]:
df1.isnull().sum()

Student    0
Marks      2
City       1
dtype: int64

7.2 Display rows containing missing values.

In [19]:
print("Row containing null values:")
df1[df1.isnull().any(axis=1)]

Row containing null values:

  Student  Marks     City
1       B    NaN  Chennai
2       C   92.0      NaN
4       E    NaN   Mumbai

7.3 Replace missing marks with average marks.

In [47]:
df1['Marks'] = df1['Marks'].fillna(df1['Marks'].mean())
df1

  Student  Marks       City
0       A   85.0   Hyderbad
2       C   92.0    Unknown
3       D   78.0  Bangalore

7.4 Replace missing city values with "Unknown".

In [21]:
df1['City'] = df1['City'].fillna("Unknown")
df1

  Student  Marks       City
0       A   85.0   Hyderbad
1       B    NaN    Chennai
2       C   92.0    Unknown
3       D   78.0  Bangalore
4       E    NaN     Mumbai

7.5 Drop rows having any missing value.

In [22]:
df1

  Student  Marks       City
0       A   85.0   Hyderbad
1       B    NaN    Chennai
2       C   92.0    Unknown
3       D   78.0  Bangalore
4       E    NaN     Mumbai

 7.6 Drop rows only if Marks is missing.

In [23]:
df1.dropna(inplace=True)

In [24]:
df1

  Student  Marks       City
0       A   85.0   Hyderbad
2       C   92.0    Unknown
3       D   78.0  Bangalore

In [25]:
df1.dropna(subset=['Marks'], inplace=True)

In [26]:
df1

  Student  Marks       City
0       A   85.0   Hyderbad
2       C   92.0    Unknown
3       D   78.0  Bangalore

8. Create the following dataframe

| Order_ID | Product | Category    | Sales |
| -------- | ------- | ----------- | ----- |
| 1        | Laptop  | Electronics | 50000 |
| 2        | Mobile  | Electronics | 25000 |
| 3        | Chair   | Furniture   | 8000  |
| 4        | Table   | Furniture   | 12000 |
| 5        | Laptop  | Electronics | 55000 |
| 6        | Chair   | Furniture   | 9000  |

In [27]:
df2=pd.DataFrame({
    "Order_ID ":[1,2,3,4,5,6],
    "Product":["Laptop","Mobile","Chair","Table","Laptop","Chair"],
    "Category":["Electronics","Electronics","Furniture","Furniture","Electronics","Furniture"],
    "Sales":[50000,25000,8000,12000,55000,9000]
})

In [28]:
df2

   Order_ID  Product     Category  Sales
0          1  Laptop  Electronics  50000
1          2  Mobile  Electronics  25000
2          3   Chair    Furniture   8000
3          4   Table    Furniture  12000
4          5  Laptop  Electronics  55000
5          6   Chair    Furniture   9000

8.1 Find total sales by Category.

In [29]:
df2.groupby('Category')['Sales'].sum()

Category
Electronics    130000
Furniture       29000
Name: Sales, dtype: int64

8.2 Find average sales by Category.

In [30]:
df2.groupby('Category')['Sales'].mean()

Category
Electronics    43333.333333
Furniture       9666.666667
Name: Sales, dtype: float64

8.3 Find maximum sales by Category.

In [31]:
df2.groupby('Category')['Sales'].max()

Category
Electronics    55000
Furniture      12000
Name: Sales, dtype: int64

8.4 Find minimum sales by Category.

In [32]:
df2.groupby('Category')['Sales'].min()

Category
Electronics    25000
Furniture       8000
Name: Sales, dtype: int64

 8.5 Find number of orders in each Category.

In [33]:
df2.groupby('Category')['Sales'].value_counts()

Category     Sales
Electronics  25000    1
             50000    1
             55000    1
Furniture    8000     1
             9000     1
             12000    1
Name: count, dtype: int64

8.6 Find total sales for each Product.

In [34]:
df2['Category'].value_counts()

Category
Electronics    3
Furniture      3
Name: count, dtype: int64

In [35]:
df2.groupby('Product')['Sales'].sum()

Product
Chair      17000
Laptop    105000
Mobile     25000
Table      12000
Name: Sales, dtype: int64

9. Create two Dataframes

| Emp_ID | Name  |
| ------ | ----- |
| 101    | Ravi  |
| 102    | Priya |
| 103    | Kiran |
| 104    | Sneha |

In [36]:
df3=pd.DataFrame({
    "Emp_ID":[101,102,103,104],
    "Name":["Rahul","Priya","Kiran","Sneha"]
})

In [37]:
df3

   Emp_ID   Name
0     101  Rahul
1     102  Priya
2     103  Kiran
3     104  Sneha


| Emp_ID | Department |
| ------ | ---------- |
| 101    | IT         |
| 102    | HR         |
| 103    | Finance    |
| 105    | Marketing  |

In [38]:
df4=pd.DataFrame({
    "Emp_ID":[101,102,103,105],
    "Department":["IT","HR","Finance","Marketing"]

})

In [39]:
df4

   Emp_ID Department
0     101         IT
1     102         HR
2     103    Finance
3     105  Marketing

9.1 Perform Inner Join.

In [40]:
pd.merge(df3, df4, how='inner')

   Emp_ID   Name Department
0     101  Rahul         IT
1     102  Priya         HR
2     103  Kiran    Finance

 9.2 Perform Left Join.

In [41]:
pd.merge(df3, df4, how='left')

   Emp_ID   Name Department
0     101  Rahul         IT
1     102  Priya         HR
2     103  Kiran    Finance
3     104  Sneha        NaN

9.3 Perform Right Join.

In [42]:
pd.merge(df3, df4, how='right')

   Emp_ID   Name Department
0     101  Rahul         IT
1     102  Priya         HR
2     103  Kiran    Finance
3     105    NaN  Marketing

9.4 Perform Outer Join.

In [43]:
pd.merge(df3, df4, how='outer')

   Emp_ID   Name Department
0     101  Rahul         IT
1     102  Priya         HR
2     103  Kiran    Finance
3     104  Sneha        NaN
4     105    NaN  Marketing

9.5 Identify employees present in one DataFrame but not the other.

In [44]:
result = pd.merge(
    df3,
    df4,
    on='Emp_ID',
    how='outer',
    indicator=True
)

print(result[result['_merge'] != 'both'])

   Emp_ID   Name Department      _merge
3     104  Sneha        NaN   left_only
4     105    NaN  Marketing  right_only